services:
  - type: web
    name: nspindle-nodered
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: TZ
        value: Asia/Kuala_Lumpur
